drop view INCIDENCE_VIEW;

CREATE VIEW INCIDENCE_VIEW AS 
SELECT DATATYPE.CONCEPT_ID AS ID,
CNAME.NAME AS ATTRIBUTE_NAME,
DESCR.DESCRIPTION AS ATTRIBUTE_DESC,
DATATYPE.DATATYPE_ID AS DATATYPE_ID,
CLASS.CONCEPT_CLASS_ID AS CLASS_ID,
CLASS.DESCRIPTION AS CLASS_DESC,
CLASS.NAME AS ATTRIBUTE_TYPE
FROM 
CONCEPT_CLASS CLASS, CONCEPT DATATYPE, CONCEPT_DESCRIPTION DESCR, CONCEPT_NAME CNAME
WHERE DESCR.CONCEPT_ID=DATATYPE.CONCEPT_ID 
AND DATATYPE.CLASS_ID=CLASS.CONCEPT_CLASS_ID 
AND CNAME.CONCEPT_ID = DATATYPE.CONCEPT_ID;


UPDATE INCIDENCE SET MEDICATIONID_1 = -1, MEDICATIONID_2 = -1; 
